angular.module('app.services', ['ngResource'])
  .factory('Tomato', ($resource) -> $resource 'tomato')
  .factory('Break', ($resource) -> $resource 'breaks/:breakId')
  .factory('Task', ($resource) -> $resource 'tasks/:taskId')
  .factory('Work', ($resource) -> $resource 'works/:workId')
